
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import MessageBox from '../Components/MessageBox'


import Sidenav from '../Components/sidenav'
import TopNav from '../Components/TopNav'
import Wellcome from '../Components/Wellcome'




export default function Home() {
  const [selectedUser, setSelectedUser] = useState<any>(undefined);

  const [appUser, setAppUser] = useState({})

  // handle undefined Problem



  useEffect(() => {

    const userData = localStorage.getItem('user')
    if (userData) {
      setAppUser(JSON.parse(userData))
    }


  }, [])




  return (
    <>
      <Head>
        <title>ChatsSkoot - Realtime Chat application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main max-h-screen w-full bg-bgPrimary bg-fixed">
        <Sidenav
          selectedUser={selectedUser}
          setSelectedUser={setSelectedUser}
        />

{
  !selectedUser ? <Wellcome/> :
  
  <main className="main-content relative  max-h-screen w-full md:pl-[280px] lg:pl-[280px]">
  <div className="z-50 relative">
    <div className='chatContainer h-screen grid '>

      <div className="nav text-white">

        {/* topNav sectiopn  */}

        <TopNav
          appUser={appUser}
          selectedUser={selectedUser}
        />

      </div>
      <div className="chats text-white flex flex-col-reverse px-5 overflow-y-scroll">

        <MessageBox
          appUser={appUser}
        />



      </div>

      {/* message options */}

      <div className="msgBox grid  content-center items-center gap-6  text-white">



        <Image width={70} height={70} src='/images/attachment.png' alt='attachment' />



        <div>
          <input type="text" className='w-full p-2 rounded outline-none bg-bgSecondary' placeholder="Type a message" />
        </div>

      </div>




    </div>
  </div>
  <div>

  </div>
</main>
}

      </div>
    </>
  )
}
