import Head from 'next/head'

import { Inter } from '@next/font/google'
import Sidenav from '../Components/sidenav'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatsSkoot - Realtime Chat application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="main  max-h-screen w-full bg-bgPrimary bg-fixed">
    <Sidenav/>
    <main className="main-content relative  min-h-screen w-full md:pl-[280px] lg:pl-[310px]">
        <div className="z-50 relative">
        <div>content</div>
        </div>
        <div>
          <div className="wave_anim ">
            <div className="wave wave1"></div>
            <div className="wave wave2"></div>
            <div className="wave wave3"></div>
            <div className="wave wave4"></div>
          </div>
        </div>
      </main>
    </div>
    </>
  )
}
