import Head from 'next/head';
import React from 'react';

const login = () => {

    const handleSubmit = (e) => {
        e.preventDefault()
     
        const form = e.target
        const email = form.email.value 
        const password = form.password.value
        const data = {email: email, password: password}

        // login authenticaton

    }

    return (
        <>
             <Head>
                <title>ChatsSkoot - Create New User</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <form onSubmit={handleSubmit} className='form' >


<input type="email" name="email" placeholder='type your Email' required /> <br /><br />
<input type="password" name="password" placeholder='type your Password' required /> <br /><br />
<input type="submit" value="Login" />


</form>
        </>
    );
};

export default login;