import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React from 'react';

const login = () => {
    const router = useRouter()

    const handleSubmit = (e) => {
        e.preventDefault()
     
        const form = e.target
        const username = form.email.value 
        const password = form.password.value
        const data = {username: username, password: password}

        // login authenticaton

        axios.post(`http://localhost:5000/api/auth/login`,data)
.then(data=> {
    const {status,msg} = data.data

    if(!status){
        alert(msg)
    }else{
        alert('successfully logged in')
        router.push('/');
    }

   

})
.catch(err=>console.error(err.message))

    }

    return (
        <>
             <Head>
                <title>ChatsSkoot - Create New User</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <form onSubmit={handleSubmit} className='form' >


<input type="username" name="email" placeholder='type your Email' required /> <br /><br />
<input type="password" name="password" placeholder='type your Password' required /> <br /><br />
<input type="submit" value="Login" />


</form>
        </>
    );
};

export default login;