import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';



const signup = () => {

    const handleSubmit:React.FormEventHandler<HTMLFormElement> = async(e) => {
     e.preventDefault()
     
     const form = e.target as HTMLFormElement
     const name = form.fullName.value 
     const username = form.username.value 
     const email = form.email.value
     const password = form.password.value
     const data = {
        name,email,password,username
     }
// call api to post data

axios.post(`http://localhost:5000/api/auth/signup`,data)
.then(data=> console.log(data))
.catch(err=>console.error(err.message))


    }


    return (
        <>
            <Head>
                <title>ChatsSkoot - Create New User</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

            <div className='bg-bgSecondary'>
            <div className="container">

    <div className="panel">
        <form className='form' onSubmit={handleSubmit}>

        <div className="panel-group">
            <input className="input" type="text" name='fullName' required />
            <span className="border"></span>
            <label>Name</label>
        </div>
        <div className="panel-group">
            <input className="input" type="username" name='username' required />
            <span className="border"></span>
            <label>Username</label>
        </div>
        <div className="panel-group">
            <input className="input" type="email" name='email' required />
            <span className="border"></span>
            <label>Email</label>
        </div>

        <div className="panel-group">
            <input className="input" name='password' type="password" required />
            <span className="border"></span>
            <label>Password</label>
        </div>

        <button type="submit">Signup</button>

        </form>
        <div className="panel-footer">
            <p><Link href={''} >Forgotten password?</Link></p>
            <p>Not a member? <Link href="/signup">Sign up now</Link></p>
        </div>
    </div>
</div>


        </div>

            </main>
        </>
    );
};

export default signup;